openapi: "3.0.0"
info:
  version: 1.0.0
  title: Geizhals Mega Deals
  description: Application that crawls incredible Deals from the Geizhals website
  license:
    name: MIT
servers:
  - url: https://cooledomain.io
paths:
  /deals:
    get:
      summary: List items of category from start to limit
      operationId: listItems
      tags:
        - items
      parameters:
        - name: start
          in: query
          description: Index from where to start listing items
          required: true
          schema:
            type: integer
            format: int32
        - name: limit
          in: query
          description: Amount of items to list after start index
          required: true
          schema:
            type: integer
            format: int32
        - name: category
          in: query
          description: Category of the items to list
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: List of Deals
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Deals"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Deal:
      required:
        - _id
        - name
        - category
        - date
        - percent
        - link
        - price_new
        - price_old
        - seller
        - createdAt
      properties:
        _id:
          type: string
        name:
          type: string
        category:
          type: integer
          format: int32
          exclusiveMaximum: false
          minimum: 1
          maximum: 14
        date:
          type: string
          format: date-time
        percent:
          type: string
        link:
          type: string
        price_new:
          type: string
        price_old:
          type: string
        seller:
          type: string
        createdAt:
          type: string
          format: date-time
    Deals:
      type: array
      items:
        $ref: "#/components/schemas/Deal"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
